config/routes.rb
MenuMaster::Application.routes.draw do
  root 'static_pages#home'
  resources :users do
    member do
      get :following, :followers
    end
    member do
      resources :microposts, only: [] do
        collection do
          get :activity
        end
      end
    end
    resources :meals
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy, :index] 
  resources :relationships, only: [:create, :destroy]
  resources :foods
  resources :food_imports, only: [:new, :create]
  resources :recipes do
    resources :ingredients
    collection do
      get :browse
    end
  end
  
  get "signup/"  => 'users#new'

  scope controller: :static_pages do
    get "help/"    => :help
    get "about/"   => :about
    get "contact/" => :contact
    get "home_recipe_nav" => :recipe_nav
  end

  get "signin/"  => 'sessions#new'
  delete "signout/" => 'sessions#destroy'

  get "newsfeed/" => 'microposts#index'
  
  get 'users/:id/microposts' => 'microposts#user', as: :user_microposts
  get 'users/:id/recipes'    => 'recipes#user',    as: :user_recipes

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @feed_items = current_user.feed.paginate(page: params[:page])
      @micropost = current_user.microposts.build
    end
  end

  def help
  end

  def about
  	
  end

  def contact
  	
  end

  def recipe_nav
    respond_to do |format|
      format.js
      format.html
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

	
end

app/views/static_pages/_recipe_nav.html.erb
<div class="home_menu_item">
	<h1><%= link_to "My Recipes", recipes_path %></h1>
</div>
<div class="home_menu_item">
	<h1><%= link_to "Browse", browse_recipes_path %></h1>
</div>

app/views/static_pages/_signed_in.html.erb
<div class="row-fluid">
	<aside class="col-md-4">
		<section>
			<%= render 'shared/user_info' %>
		</section>
		<section>
			<%= render 'shared/stats' %>
		</section>
		<section>
			<%= render 'shared/micropost_form' %>
		</section>
	</aside>
	<div class="col-md-8" id="home_menu">
		<div class="home_menu_item">
			<h1><%= link_to "Recipes", home_recipe_nav_path, remote: true %></h1>
		</div>
		<div class="home_menu_item">
			<h1>Macro Tracker</h1>
		</div>
		<div class="home_menu_item">
			<h1><%= link_to "Newsfeed", newsfeed_path %></h1>
		</div>
	</div>
</div>

app/views/static_pages/_splash.html.erb
<div class="center hero-unit">
	<h1>MenuMaster</h1>

	<h2>
		Let's party
	</h2>
	<%= link_to "Sign up", signup_path, class:"btn btn-large" %>
</div>

app/views/static_pages/about.html.erb
<% provide :title, 'About' %>

<h1>About</h1>

<p>I made this.</p>

app/views/static_pages/contact.html.erb
<%= provide :title, 'Contact' %>

<div class="center">
  <h1>Contact</h1>
  <p>Don't bother...</p>
</div>

app/views/static_pages/help.html.erb
<% provide :title, 'Help' %>

<div class='center'>
	<h1>Help</h1>
	<h2>
		I don't know what you expected, but you won't find it here.
	<h2>
</div>

app/views/static_pages/home.html.erb
<% provide :title, '' %>

<% if signed_in? %>
	<%= render 'static_pages/signed_in' %>
<% else %>
	<%= render 'static_pages/splash' %>
<% end %>

app/views/static_pages/recipe_nav.html.erb
<div class="row">
	<div class="span6 offset3">
		<%= render 'recipe_nav' %>
	</div>
</div>

app/views/static_pages/recipe_nav.js.erb
$("#home_menu").html("<%= escape_javascript(render('recipe_nav')) %>")