config/routes.rb
MenuMaster::Application.routes.draw do
  root 'static_pages#home'
  resources :users do
    member do
      get :following, :followers
    end
    member do
      resources :microposts, only: [] do
        collection do
          get :activity
        end
      end
    end
    resources :meals
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy, :index] 
  resources :relationships, only: [:create, :destroy]
  resources :foods
  resources :food_imports, only: [:new, :create]
  resources :recipes do
    resources :ingredients
    collection do
      get :browse
    end
  end
  
  get "signup/"  => 'users#new'

  scope controller: :static_pages do
    get "help/"    => :help
    get "about/"   => :about
    get "contact/" => :contact
    get "home_recipe_nav" => :recipe_nav
  end

  get "signin/"  => 'sessions#new'
  delete "signout/" => 'sessions#destroy'

  get "newsfeed/" => 'microposts#index'
  
  get 'users/:id/microposts' => 'microposts#user', as: :user_microposts
  get 'users/:id/recipes'    => 'recipes#user',    as: :user_recipes

  

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	extend FriendlyId
	include Search
	friendly_id :slug_candidates, use: [:slugged, :history]
	belongs_to :user
	validates :name, presence: true
	validates :slug, presence: true, uniqueness: { case_sensitive: false }
	has_many :ingredients, dependent: :destroy


	def should_generate_new_friendly_id?
		name_changed?
	end

	def slug_candidates
		[
			"#{name} by #{user.username}",
			"#{name} by #{user.username} #{Time.now.to_s}"
		]
	end

	def set_nutritional_values
		self.update_attributes(calories: ingredients.sum(:calories),
			                     carbs: ingredients.sum(:carbs),
			                     protein: ingredients.sum(:protein),
			                     fat: ingredients.sum(:fat))
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :signed_in_user, except: [:show, :user]
	before_action :correct_recipe, only: [:edit, :update, :destroy]

	def new
		@recipe = current_user.recipes.build
	end

	def create
		@recipe = current_user.recipes.build(recipe_params)
		if @recipe.save
			flash[:success] = "Recipe created"
			redirect_to @recipe
		else
			render :new
		end
	end

	def edit
		respond_to do |format|
			format.html
			format.js
		end
	end

	def update
		if @recipe.update_attributes(recipe_params)
			respond_to do |format|
				format.html do 
					flash[:success] = "Recipe updated."
					redirect_to @recipe
				end
				format.js
			end
		else
			render :edit, id: @recipe.id, format: :js
		end
	end

	def show
		@recipe = Recipe.friendly.find(params[:id])
		@ingredients = table_items(@recipe.ingredients)
		@title = "#{@recipe.name} by #{@recipe.user.username}"
		respond_to do |format|
			format.html do
				if request.path != recipe_path(@recipe)
					redirect_to @recipe
				end
			end
			format.js
		end
	end

	def index
		@title = "My Recipes"
		@recipes = table_items(current_user.recipes)
		respond_to do |format|
			format.html
			format.js { render :table }
		end
	end

	def destroy
		@recipe.destroy
		redirect_to recipes_path
	end

	def browse
		@title = "Browse Recipes"
		@recipes = table_items(Recipe)
		respond_to do |format|
			format.html { render :index }
			format.js   { render :table }
		end
	end

	def user
		@user = User.find_by_username(params[:id])		
		@recipes = table_items(@user.recipes)
		@title = @user.username + "'s Recipes"
		respond_to do |format|
			format.html { render :index }
			format.js   { render :table }
		end
	end

	private
		def recipe_params
			params.require(:recipe).permit(:name, :description)
		end

		def correct_recipe
			@recipe = current_user.recipes.friendly.find(params[:id])
		rescue
			redirect_to root_path
		end
end

app/helpers/recipes_helper.rb
module RecipesHelper

end

app/views/recipes/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name, "Name" %>
<%= f.text_field :name %>

<%= f.label :description, "Description" %>
<%= f.text_area :description %>

app/views/recipes/_recipe.html.erb
<div class="table_row" id="recipe_<%= recipe.id %>">
	<%= render 'shared/basic_info', object: recipe %>
</div>

app/views/recipes/_recipe_form.html.erb
<%= form_for recipe, remote: true do |f| %>
	<%= render 'fields', f:f %>
	<%= f.submit "Update", class: "btn btn-success btn-inline" %>
	<%= link_to "Cancel", recipe_path(recipe), class: "btn", remote: true %>
	<%= link_to "Delete", recipe_path(recipe), method: :delete, class: "btn btn-danger" %>
<% end %>

app/views/recipes/_recipe_ingredients.html.erb
<h3>
	Ingredients
</h3>
<% if current_user == @recipe.user %>
	<%= link_to "+ Add ingredients", new_recipe_ingredient_path(@recipe), class: "pull-right", remote: true %>
<% end %>
<%= form_tag recipe_path(@recipe), method: "get", 
                                   id: "recipe_search",
                                   remote: true do %>
  <%= hidden_field_tag :sort, params[:sort] %>
	<%= hidden_field_tag :direction, params[:direction] %>
	<%= render "shared/search_form" %>
<% end %>
<% if @ingredients.any? %>
	<div class="table">
		<%= render 'recipe_ingredients_table' %>
	</div>
	<%= will_paginate @ingredients %>
<% end %>

app/views/recipes/_recipe_ingredients_table.html.erb
<%= render 'shared/table_headers', object_model: Recipe, show_amount: true %>
<%= render @ingredients, recipe: @recipe %>

app/views/recipes/_recipe_sidebar.html.erb
<section>
	<h1><%= recipe.name %>
	<% if current_user == recipe.user %>
		[ <%= link_to "edit", edit_recipe_path(recipe), remote: true %> ]
	<% end %>
	</h1>
	<i>
		by <%= link_to recipe.user.username, recipe.user %>
	</i>
</section>
<section>
	<i><%= recipe.description %></i>
</section>
<section>
	<% if current_user == recipe.user %>
		<%= link_to "My Recipes", recipes_path  %>
	<% end %>
</section>

app/views/recipes/browse.html.erb
<% provide :title, "Browse Recipes" %>

<div class="row">
	<div class="span8 offset2">
		<h1>Browse Recipes</h1>
		<%= form_tag browse_recipes_path, method: "get", id: "recipes_search", class: "search" do %>
			<%= render 'shared/search_form' %>
			<div class="table" id="recipes">
				<%= render 'recipes_table' %>
			</div>
		<% end %>
		<%= will_paginate @recipes %>
	</div>
</div>

app/views/recipes/edit.html.erb
<% provide :title, "Edit Recipe" %>

<div class="row">
	<div class="span6 offset3">
		<h1>Edit Recipe</h1>
		<%= form_for @recipe do |f| %>
			<%= render 'fields', f:f %>
			<%= f.submit "Update", class: "btn btn-success btn-inline" %>
			<%= link_to "Cancel", recipe_path(@recipe), class: "btn" %>
			<%= link_to "Delete", recipe_path(@recipe), method: :delete, class: "btn btn-danger" %>
		<% end %>
	</div>
</div>

app/views/recipes/edit.js.erb
$("aside#recipe_info").html("<%= escape_javascript(render('recipe_form', recipe: @recipe)) %>")

app/views/recipes/index.html.erb
<% provide :title, @title %>

<div class="row">
	<div class="span8 offset2">
		<h1><%= @title %></h1>
		<% if params[:action] == "index" %>
			<%= link_to "+ New recipe", new_recipe_path, class: "pull-right" %>
		<% end %>
		<%= form_tag({ controller: params[:controller], action: params[:action] }, 
				             { method: "get", id: "recipes_search", class: "search_form" }) do %>
			<%= render 'shared/search_form' %>
			<div class="table" id="recipes">
				<%= render 'recipes_table' %>
			</div>
		<% end %>
	</div>
</div>

app/views/recipes/new.html.erb
<% provide :title, "New Recipe" %>

<div class="row">
	<div class="span6 offset3">
		<h1>New Recipe</h1>
		<%= form_for @recipe do |f| %>
		  
		  <%= render 'shared/error_messages', object: f.object %>

		  <%= f.label :name, "Name" %>
		  <%= f.text_field :name %>

		  <%= f.label :description, "Description" %>
		  <%= f.text_area :description %>

		  <%= f.submit "Save", class: "btn btn-large" %>
		<% end %>
	</div>
</div>

app/views/recipes/show.html.erb
<% provide :title, @title %>

<div class="row">
	<aside class="span4" id="recipe_info">
		<%= render 'recipe_sidebar', recipe: @recipe %>
	</aside>
	<div class="span8" id="ingredients">
		<%= render 'recipe_ingredients' %>
	</div>
</div>	

app/views/recipes/table.js.erb
$('#recipes').html("<%= escape_javascript(render('recipes_table')) %>")

app/views/recipes/update.js.erb
$("aside#recipe_info").html("<%= escape_javascript(render('recipe_sidebar', recipe: @recipe)) %>")