config/routes.rb
MenuMaster::Application.routes.draw do
  root 'static_pages#home'
  resources :users do
    member do
      get :following, :followers
    end
    member do
      resources :microposts, only: [] do
        collection do
          get :activity
        end
      end
    end
    resources :meals
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy, :index] 
  resources :relationships, only: [:create, :destroy]
  resources :foods
  resources :food_imports, only: [:new, :create]
  resources :recipes do
    resources :ingredients
    collection do
      get :browse
    end
  end
  
  get "signup/"  => 'users#new'

  scope controller: :static_pages do
    get "help/"    => :help
    get "about/"   => :about
    get "contact/" => :contact
    get "home_recipe_nav" => :recipe_nav
  end

  get "signin/"  => 'sessions#new'
  delete "signout/" => 'sessions#destroy'

  get "newsfeed/" => 'microposts#index'
  
  get 'users/:id/microposts' => 'microposts#user', as: :user_microposts
  get 'users/:id/recipes'    => 'recipes#user',    as: :user_recipes

  

end

app/views/shared/_basic_info.html.erb
<% if object.class == Recipe %>
	<span><%= link_to object.name, object %></span>
<% else %>
	<span><%= object.name %></span>
<% end %>
<span><%= number_with_precision object.calories, precision: 2 %></span>
<span><%= number_with_precision object.carbs, precision: 2 %></span>
<span><%= number_with_precision object.protein, precision: 2 %></span>
<span><%= number_with_precision object.fat, precision: 2 %></span>
<% if object.class == Ingredient && params[:action] != 'edit' %>
	<span><%= number_with_precision object.amount, precision: 2 %></span>
<% end %>

app/views/shared/_delete_link.html.erb
<% if current_user?(micropost.user) %>
		| <%= link_to 'delete', micropost, method: :delete,
																			 data: { confirm: "Are you sure" },
																			 title: micropost.content %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			This form contains <%= pluralize object.errors.count, "error" %>
		</div>
		<ul>
			<% object.errors.full_messages.each do |message| %>
				<li>* <%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user, size: 30), feed_item.user  %>
	<span class="user">
		<%= link_to feed_item.user.username, feed_item.user %>
	</span>
	<span class="content">
		<%= wrap(feed_item.content) %>
	</span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago
		<%= render 'shared/delete_link', micropost: feed_item %>
	</span>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| -%>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
  	<%= f.text_area :content, placeholder: "Compose new micropost" %>
  </div>
  <%= f.submit "Post", class: "btn btn-large" %>
<% end -%>

app/views/shared/_search_form.html.erb
	<div class="row-fluid">
		<%= label_tag :search, nil, class: "sr-only" %>
		<span class="col-xs-6">
			<%= text_field_tag :search, params[:search], class: "form-control" %>
		</span>
		<span class="col-xs-2">
			<%= button_tag(type: 'submit', class: "btn", name: nil) do %>
			  <span class="glyphicon glyphicon-search">
			  	<span class="sr-only">Search</span>
			  </span> 
			<% end %>
		</span>
	</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/shared/_table_headers.html.erb
<div class="table_row table_header">
	<% %w[name calories carbs protein fat].each do |column_name| %>
		<span>
			<%= sortable object_model, column_name %>
			<% if column_name != "name" %>
				(<%= (column_name == "calories") ? "kCal" : "g" %>)
			<% end %>
			<% if params[:sort] == column_name %>
				<% if params[:direction] == "asc"  %>
					<i class="icon-chevron-up"></i>
				<% else %>
					<i class="icon-chevron-down"></i>
				<% end %>
			<% end %>
		</span>
	<% end %>
	<% if show_amount %>
		<span>Amount (g)</span>
		<span></span>
	<% end %>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
	<%= gravatar_for current_user, size: 52 %>
</a>
<h1>
	<%= current_user.username %>
</h1>
<span>
	<%= link_to "view my profile", current_user %>
</span>
<span>
	<%= pluralize(current_user.microposts.count, "micropost") %>
</span>