config/routes.rb
MenuMaster::Application.routes.draw do
  root 'static_pages#home'
  resources :users do
    member do
      get :following, :followers
    end
    member do
      resources :microposts, only: [] do
        collection do
          get :activity
        end
      end
    end
    resources :meals
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy, :index] 
  resources :relationships, only: [:create, :destroy]
  resources :foods
  resources :food_imports, only: [:new, :create]
  resources :recipes do
    resources :ingredients
    collection do
      get :browse
    end
  end
  
  get "signup/"  => 'users#new'

  scope controller: :static_pages do
    get "help/"    => :help
    get "about/"   => :about
    get "contact/" => :contact
    get "home_recipe_nav" => :recipe_nav
  end

  get "signin/"  => 'sessions#new'
  delete "signout/" => 'sessions#destroy'

  get "newsfeed/" => 'microposts#index'
  
  get 'users/:id/microposts' => 'microposts#user', as: :user_microposts
  get 'users/:id/recipes'    => 'recipes#user',    as: :user_recipes

  

end

app/models/food.rb
class Food < ActiveRecord::Base
	include Search

	validates :name,     presence: true, uniqueness: { case_sensitive: false }
	validates :calories, presence: true
	validates :fat,      presence: true
	validates :carbs,    presence: true
	validates :protein,  presence: true

	def self.to_csv(options={}) 
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |food|
				csv << food.attributes.values_at(*column_names)
			end
		end
	end

	def self.accessible_attributes
		["name", "calories", "fat", "carbs", "protein"]
	end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
	before_filter :signed_in_user
	before_filter :is_admin, except: [:show, :index]

	before_filter(:only => :index) do |controller|
   controller.send(:is_admin) unless controller.request.format.html?
 	end

	def new
		@food = Food.new
	end

	def create
		@food = Food.new(food_params)
		if @food.save
			flash[:success] = "Food created."
			redirect_to foods_path
		else
			render 'new'
		end
	end

	def show
		@food = Food.find(params[:id])
	end

	def index
		@foods = table_items(Food)
		respond_to do |format|
			format.html
			format.js
			format.csv { render text: Food.to_csv }
			format.xls
		end
	end

	def edit
		@food = Food.find(params[:id])
	end

	def update
		@food = Food.find(params[:id])
		if @food.update_attributes(food_params)
			flash[:success] = "Food updated."
			redirect_to foods_path
		else
			render 'edit'
		end
	end

	def destroy
		Food.find(params[:id]).destroy
		flash[:succes] = "Food deleted."
		redirect_to foods_path
	end

	private

		def food_params
			params.require(:food).permit(:name, :carbs, :fat, :protein, :calories)
		end
end

app/views/foods/_food.html.erb
<div class="food_stats table_row" id="food_<%= food.id %>">
	<% if current_user.admin? %>
		<span>
			<div class="dropdown">
				<a href="#", id="fat-menu" class="dropdown-toggle" data-toggle="dropdown">
					<%= food.name %><b class="caret"></b>
				</a>
				<ul class="dropdown-menu pull-left">
					<li><%= link_to 'Show', food %></li>
					<li><%= link_to 'Edit', edit_food_path(food) %></li>
					<li><%= link_to 'Delete', food_path(food), method: :delete %></li>
				</ul>
			</div>
		</span>
	<% else %>
		<span><%= link_to food.name, food %></span>
	<% end %>
	<span><%= food.calories %></span>
	<span><%= food.carbs %></span>
	<span><%= food.protein %></span>
	<span><%= food.fat %></span>
</div>

app/views/foods/_food_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div id="foods" class="table">
	<div class="table_row">
		<span><%= f.label :name, "Name" %></span>
		<span><%= f.label :calories, "Calories (kcal)" %></span>
		<span><%= f.label :carbs, "Carbs (g)" %></span>
		<span><%= f.label :protein, "Protein (g)" %></span>
		<span><%= f.label :fat, "Fat (g)" %></span>
	</div>
	<div class="table_row">
	  <span><%= f.text_field :name %></span>
	  <span><%= f.text_field :calories %></span>
	  <span><%= f.text_field :carbs %></span>
	  <span><%= f.text_field :protein %></span>
	  <span><%= f.text_field :fat %></span>
	</div>
</div>

app/views/foods/_foods_table.html.erb
<%= hidden_field_tag :sort, params[:sort] %>
<%= hidden_field_tag :direction, params[:direction] %>
<%= render 'shared/table_headers', object_model: Food, show_amount: false %>
<%= render @foods %>
<%= will_paginate @foods %>

app/views/foods/edit.html.erb
<% provide :title, "Edit food" %>

<div class="row">
	<div class="span8 offset2">
		<h1>Edit Food</h1>
		<%= form_for @food do |f| %>
			<%= render 'food_fields', f:f %>
			<%= f.submit 'Update food', class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/foods/index.html.erb
<% provide :title, "All foods" %>

<div class="row">
	<div class="span8 offset2">
		<h1>All foods</h1>
		<h2>Nutritional value per 100g</h2>
		<% if current_user.admin? %>
			<div id="add_food_link">
				<%= link_to "+ Add food", new_food_path %>
			</div>
		<% end %>
		<%= form_tag foods_path, method: "get", id: "foods_search", class: "search" do %>
			<%= render 'shared/search_form', path: foods_path %>
			<div id="foods" class="table">
				<%= render 'foods_table' %>
			</div>
		<% end %>
		<% if current_user.admin? %>
			<div class="btn-group">
				<a href="#" class="btn btn-mini dropdown dropdown-toggle" data-toggle="dropdown">
					Export<span class="caret"></span>
				</a>
					<ul class="dropdown-menu">
						<li><%= link_to "CSV", foods_path(format: "csv") %> </li>
						<li><%= link_to "XLS", foods_path(format: "xls") %></li>
					</ul>
				<%= link_to "Import", new_food_import_path, class: "btn btn-mini" %>
			</div>
		<% end %>
	</div>
</div>

app/views/foods/index.js.erb
$(".table").html("<%= escape_javascript(render('foods_table')) %>")

app/views/foods/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Calories</Data></Cell>
        <Cell><Data ss:Type="String">Carbs</Data></Cell>
        <Cell><Data ss:Type="String">Protein</Data></Cell>
        <Cell><Data ss:Type="String">Fat</Data></Cell>
      </Row>
    <% @foods.each do |food| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= food.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= food.name %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= food.calories %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= food.carbs %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= food.protein %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= food.fat %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/foods/new.html.erb
<% provide :title, "Create food" %>

<div class="row">
	<div class="span6 offset3">
		<h1>Create food</h1>
		<%= form_for @food do |f| %>
		  <%= render 'food_fields', f:f %>
		  <%= f.submit "Create food", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/foods/show.html.erb
<% provide :title, @food.name %>

<div class="row">
	<div class="span6 offset3">
		<h1><%= @food.name %></h1>
		<h2>Nutrient Information (per 100g):</h2>
		<div class="stats">
			<span>
				Total Calories:
				<strong class="stat">
					<%= @food.calories %> kcal
				</strong>
			</span>
			<span>
				Carbs:
				<strong class="stat">
					<%= @food.carbs %>g
				</strong>
			</span>
			<span>
				Protein:
				<strong class="stat">
					<%= @food.protein %>g
				</strong>
			</span>
			<span>
				Fat:
				<strong class="stat">
					<%= @food.fat %>g
				</strong>
			</span>
		</div>
	</div>
</div>